// <auto-generated />
using System;
using EfCoreMany2ManyBugReproduction;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EfCoreMany2ManyBugReproduction.Migrations
{
    [DbContext(typeof(TestContext))]
    partial class TestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("EfCoreMany2ManyBugReproduction.Entities.BookA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropertyForA")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BookAs");
                });

            modelBuilder.Entity("EfCoreMany2ManyBugReproduction.Entities.BookB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropertyForB")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BookBs");
                });

            modelBuilder.Entity("EfCoreMany2ManyBugReproduction.Entities.BookTag", b =>
                {
                    b.Property<int>("BookAId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BookBId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookAId", "TagId");

                    b.HasIndex("BookBId");

                    b.HasIndex("TagId");

                    b.ToTable("BookTags");
                });

            modelBuilder.Entity("EfCoreMany2ManyBugReproduction.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("EfCoreMany2ManyBugReproduction.Entities.BookTag", b =>
                {
                    b.HasOne("EfCoreMany2ManyBugReproduction.Entities.BookA", "BookA")
                        .WithMany("Tags")
                        .HasForeignKey("BookAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EfCoreMany2ManyBugReproduction.Entities.BookB", null)
                        .WithMany("Tags")
                        .HasForeignKey("BookBId");

                    b.HasOne("EfCoreMany2ManyBugReproduction.Entities.Tag", "Tag")
                        .WithMany("Books")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
